import { describe, expect, it } from 'vitest'

import { detectDdlCapabilities } from './ddl-capabilities.js'
import { DdlValidationError } from './ddl-command.js'
import { buildDdlStatements } from './ddl-sql-builder.js'

const postgres96 = detectDdlCapabilities('postgres', '9.6.24')
const postgres17 = detectDdlCapabilities('postgres', '17.5')
const mysql56 = detectDdlCapabilities('mysql', '5.6.51')
const mysql84 = detectDdlCapabilities('mysql', '8.4.5')

describe('buildDdlStatements', () => {
  it('建立 PostgreSQL schema 與含結構化 defaults 的 table', () => {
    expect(buildDdlStatements(postgres17, {
      kind: 'create-schema',
      name: 'sales"ops',
      owner: 'db_owner',
    })).toEqual(['CREATE SCHEMA "sales""ops" AUTHORIZATION "db_owner"'])

    expect(buildDdlStatements(postgres17, {
      kind: 'create-table',
      schema: 'sales"ops',
      name: 'orders',
      columns: [{
        name: 'id',
        type: { name: 'bigint' },
        nullable: false,
        identity: true,
      }, {
        name: 'label',
        type: { name: 'varchar', length: 120 },
        nullable: false,
        default: { kind: 'literal', value: "customer's order" },
      }, {
        name: 'created_at',
        type: { name: 'timestamptz' },
        nullable: false,
        default: { kind: 'function', name: 'current_timestamp' },
      }],
    })).toEqual([
      'CREATE TABLE "sales""ops"."orders" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "label" varchar(120) DEFAULT \'customer\'\'s order\' NOT NULL, "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL)',
    ])
  })

  it('拒絕 PostgreSQL 9.6 不支援的 identity 與白名單外型別', () => {
    expect(() => buildDdlStatements(postgres96, {
      kind: 'add-column',
      schema: 'public',
      table: 'orders',
      column: { name: 'id', type: { name: 'bigint' }, nullable: false, identity: true },
    })).toThrow(new DdlValidationError('DDL_CAPABILITY_UNSUPPORTED'))
    expect(() => buildDdlStatements(postgres17, {
      kind: 'add-column',
      schema: 'public',
      table: 'orders',
      column: { name: 'payload', type: { name: 'vendor_magic' }, nullable: true },
    })).toThrow(new DdlValidationError('DDL_TYPE_UNSUPPORTED'))
  })

  it('建立 PostgreSQL partitioned parent table並拒絕不支援的方言', () => {
    expect(buildDdlStatements(postgres17, {
      kind: 'create-table', schema: 'public', name: 'events',
      columns: [{ name: 'id', type: { name: 'bigint' }, nullable: false }],
      partitionBy: { method: 'range', expression: 'id' },
    })).toEqual([
      'CREATE TABLE "public"."events" ("id" bigint NOT NULL) PARTITION BY RANGE (id)',
    ])
    expect(() => buildDdlStatements(postgres96, {
      kind: 'create-table', schema: 'public', name: 'events',
      columns: [{ name: 'id', type: { name: 'bigint' }, nullable: false }],
      partitionBy: { method: 'range', expression: 'id' },
    })).toThrow(new DdlValidationError('DDL_CAPABILITY_UNSUPPORTED'))
    expect(() => buildDdlStatements(mysql84, {
      kind: 'create-table', schema: 'app', name: 'events',
      columns: [{ name: 'id', type: { name: 'bigint' }, nullable: false }],
      partitionBy: { method: 'range', expression: 'id' },
    })).toThrow(new DdlValidationError('DDL_CAPABILITY_UNSUPPORTED'))
  })

  it('以結構化 sequence default 還原 PostgreSQL 9.6 serial 語意', () => {
    expect(buildDdlStatements(postgres96, {
      kind: 'create-table',
      schema: 'public',
      name: 'orders',
      columns: [{
        name: 'id',
        type: { name: 'bigint' },
        nullable: false,
        default: { kind: 'sequence', schema: 'public', name: 'orders_id_seq' },
      }],
      primaryKey: ['id'],
    })).toEqual([
      `CREATE TABLE "public"."orders" ("id" bigint DEFAULT nextval('"public"."orders_id_seq"'::regclass) NOT NULL, PRIMARY KEY ("id"))`,
    ])
    expect(() => buildDdlStatements(mysql56, {
      kind: 'add-column', schema: 'app', table: 'orders',
      column: {
        name: 'id', type: { name: 'bigint' }, nullable: false,
        default: { kind: 'sequence', schema: 'public', name: 'orders_id_seq' },
      },
    })).toThrow(new DdlValidationError('DDL_CAPABILITY_UNSUPPORTED'))
  })

  it('建立 MySQL 5.6 table 並限制 storage options 為結構化值', () => {
    expect(buildDdlStatements(mysql56, {
      kind: 'create-table',
      schema: 'app',
      name: 'orders',
      columns: [{
        name: 'id',
        type: { name: 'bigint' },
        nullable: false,
        identity: true,
      }, {
        name: 'title',
        type: { name: 'varchar', length: 255 },
        nullable: false,
      }],
      primaryKey: ['id'],
      engine: 'InnoDB',
      charset: 'utf8mb4',
      collation: 'utf8mb4_unicode_ci',
    })).toEqual([
      'CREATE TABLE `app`.`orders` (`id` bigint AUTO_INCREMENT NOT NULL, `title` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    ])

    expect(() => buildDdlStatements(mysql56, {
      kind: 'create-table',
      schema: 'app',
      name: 'invalid_identity',
      columns: [{ name: 'id', type: { name: 'bigint' }, nullable: false, identity: true }],
    })).toThrow(new DdlValidationError('DDL_INVALID_OPTION'))
  })

  it('MySQL 5.6 rename column要求完整定義，8.4使用原生語法', () => {
    expect(() => buildDdlStatements(mysql56, {
      kind: 'rename-column',
      schema: 'app',
      table: 'orders',
      from: 'old_name',
      to: 'new_name',
    })).toThrow(new DdlValidationError('DDL_COLUMN_DEFINITION_REQUIRED'))

    expect(buildDdlStatements(mysql56, {
      kind: 'rename-column',
      schema: 'app',
      table: 'orders',
      from: 'old_name',
      to: 'new_name',
      definition: { name: 'new_name', type: { name: 'varchar', length: 80 }, nullable: true },
    })).toEqual([
      'ALTER TABLE `app`.`orders` CHANGE COLUMN `old_name` `new_name` varchar(80) NULL',
    ])
    expect(buildDdlStatements(mysql84, {
      kind: 'rename-column',
      schema: 'app',
      table: 'orders',
      from: 'old_name',
      to: 'new_name',
    })).toEqual([
      'ALTER TABLE `app`.`orders` RENAME COLUMN `old_name` TO `new_name`',
    ])
  })

  it('create與rename免確認，所有drop都要求明確確認', () => {
    expect(buildDdlStatements(postgres96, {
      kind: 'rename-table', schema: 'public', from: 'orders', to: 'archived_orders',
    })).toEqual(['ALTER TABLE "public"."orders" RENAME TO "archived_orders"'])
    expect(() => buildDdlStatements(postgres96, {
      kind: 'drop-table', schema: 'public', name: 'orders', confirmed: false,
    })).toThrow(new DdlValidationError('DDL_CONFIRMATION_REQUIRED'))
    expect(buildDdlStatements(mysql56, {
      kind: 'drop-column', schema: 'app', table: 'orders', name: 'legacy', confirmed: true,
    })).toEqual(['ALTER TABLE `app`.`orders` DROP COLUMN `legacy`'])
  })

  it('拒絕任意 storage token、無效型別參數及非白名單 default function', () => {
    expect(() => buildDdlStatements(mysql84, {
      kind: 'create-database', name: 'app', charset: 'utf8mb4; DROP DATABASE app',
    })).toThrow(new DdlValidationError('DDL_INVALID_OPTION'))
    expect(() => buildDdlStatements(postgres17, {
      kind: 'add-column', schema: 'public', table: 'orders',
      column: { name: 'label', type: { name: 'varchar', length: 0 }, nullable: true },
    })).toThrow(new DdlValidationError('DDL_INVALID_TYPE_ARGUMENT'))
    expect(() => buildDdlStatements(postgres17, {
      kind: 'add-column', schema: 'public', table: 'orders',
      column: {
        name: 'created_at', type: { name: 'timestamp' }, nullable: false,
        default: { kind: 'function', name: 'pg_sleep' },
      },
    })).toThrow(new DdlValidationError('DDL_INVALID_DEFAULT'))
  })
})
